server {

    listen 80;
    listen [::]:80;

    server_name colinpmurphy.com www.colinpmurphy.com;

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/home/personalSite/flask/flask.sock;
    }
}